#!/bin/sh
cd "${0%/*}" || exit
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions
#------------------------------------------------------------------------------

runApplication blockMesh

runApplication decomposePar

runParallel snappyHexMesh -overwrite

restore0Dir -processor

runParallel patchSummary

runParallel potentialFoam -writephi

runParallel checkMesh -writeFields '(nonOrthoAngle)' -constant

runParallel $(getApplication)

runApplication reconstructParMesh -constant
runApplication reconstructPar -latestTime

#------------------------------------------------------------------------------
