#!/bin/sh
cd "${0%/*}" || exit
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions
#------------------------------------------------------------------------------

cleanCase0
rm -rf logs

# leave constant/triSurface alone — kitten.stl is a symlink to ../../../../geometry/

#------------------------------------------------------------------------------
